# Generated by Django 2.1.5 on 2019-01-19 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.Employee'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='store_type',
            field=models.SmallIntegerField(choices=[(1, 'store1'), (2, 'store2'), (3, 'store3')], default=1),
        ),
    ]
