# Generated by Django 2.1.5 on 2019-01-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='doc',
            field=models.FileField(null=True, upload_to='doc/', verbose_name='Employee Upload List'),
        ),
    ]
