# Generated by Django 2.1.5 on 2019-01-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190119_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.SmallIntegerField(choices=[(1, 'add'), (2, 'multiply')], default=1)),
                ('task', models.CharField(max_length=65, null=True)),
                ('result', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
